services:
  DiscordBot:
    build:
      context: .
      platforms:
        - linux/amd64
    image: ${IMAGE_NAME:-discordbot-euroscipy}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-discordbot-euroscipy}
    volumes:
      - ./.secrets:/home/bot/.secrets:ro
      - ./config.toml:/home/bot/discord_bot/config.toml:ro
      - ./registered_log.txt:/home/bot/registered_log.txt
      - ./discord_ticket_log.txt:/home/bot/discord_ticket_log.txt
      - ./posted_jobs.txt:/home/bot/posted_jobs.txt
    logging:
      driver: journald
    restart: unless-stopped
